apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: prj-deployment-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: "$(AWS_ACCOUNT_ID).dkr.ecr.ap-southeast-1.amazonaws.com/deployment-mgmt-dev-backend-svc-ecr:backend-service-dev-v1.0.1"
        ports:
        - containerPort: 8082
        env:
        - name: AWS_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: deployment-mgmt-dev-secrets
              key: aws-account-id

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prj-deployment-mgmt
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
  - port: 8082
    targetPort: 8082
