apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: prj-deployment-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: 774305578623.dkr.ecr.ap-southeast-1.amazonaws.com/deployment-mgmt-dev-backend-svc-ecr:backend-service-dev-v1.0.1
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prj-deployment-mgmt
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
  - port: 8082
    targetPort: 8082
