apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: prj-deployment-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: "$(AWS_ACCOUNT_ID).dkr.ecr.ap-southeast-1.amazonaws.com/deployment-mgmt-dev-api-gateway-ecr:api-gateway-dev-v1.0.1"
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: deployment-mgmt-dev-secrets
              key: aws-account-id

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: prj-deployment-mgmt
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
