apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-database-entity
  namespace: prj-deployment-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-database-entity
  template:
    metadata:
      labels:
        app: mongodb-database-entity
    spec:
      containers:
        - name: mongodb-database-entity
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongodb_root_u"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "mongodb_root_p"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-database-entity
  namespace: prj-deployment-mgmt
spec:
  selector:
    app: mongodb-database-entity
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
